server:
  port: 9091
spring:
  application:
    name: AR-API
  boot:
    admin:
      client:
        url: http://localhost:9090/
 
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rhis
    username: root
    password: Password123^
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
        
   
  
        
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'
  
        
