server:
  port: 9091
spring:
  application:
    name: AR-API
  boot:
    admin:
      client:
        url: http://localhost:9090/
 
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  
        
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'
  
        
