server:
  port: 3333
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
       - id: ar-api
         uri: lb://AR-API
         predicates: 
          - Path=/ar
       - id: dc-api
         uri: lb://DC-API
         predicates: 
          - Path=/dc
  application:
    name: CLOUD-GATEWAY-API 
  main:
    web-application-type: reactive 