server:
  port: 3337
spring:
  application:
    name: CO-API
  boot:
    admin:
      client:
        url: http://localhost:8081/
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rhis
    username: root
    password: Password123^
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
